### PR TITLE
charactercount => display an error when maxlength is not provided

### PR DESCRIPTION
**Pull request by Mboulianne**
## `@ulaval/modul-components`
# PR Checklist

- [x] Provide a small description of the changes introduced by this PR
character-count will now display an error when max-length is not provided
text-area threshold prop renamed to character-count-threshold
text-field threshold prop renamed to character-count-threshold
- [x] Include links to issues
https://jira.dti.ulaval.ca/browse/MODUL-75
- [ ] Openshift deployment requested

- [x] Include this section in the release notes
- text-area threshold prop renamed to character-count-threshold
- text-field threshold prop renamed to character-count-threshold
- [ ] Other info

### CODE REVIEW

**Comment by jipigi** [comment]
Les tests sont ajoutés dans le sandbox, de mon coté tout est OK.

**Comment by Mboulianne** [comment]
@jipigi "Les tests sont ajoutés dans le sandbox, de mon coté tout est OK."

tu t'es fait ta propre branche?  pCq je vois pas ton commit :)

**Comment by jipigi** [comment]
Je suis vraiment trop habitué à SVN! Le push est fait ;)

**Comment by Mboulianne** [comment]
@jipigi  good job! ;)

**Pull request merged**
